bin/storjshare-create.js, bin/storjshare-daemon.js, bin/storjshare-destroy.js, bin/storjshare-killall.js, bin/storjshare-logs.js, bin/storjshare-restart.js, bin/storjshare-start.js, bin/storjshare-status.js, bin/storjshare-stop.js, lib/api.js, package.json, test/api.unit.js
* Closes #3 
* Closes #5 
* Closes #6
=> Windows + Other Path Related Bugs

lib/api.js, package.json, script/farmer.js
* Closes #29 
* Depends https://github.com/Storj/data-api/pull/7 & https://github.com/Storj/pullypusher/pull/7
=> v2.1.1 (Telemetry Reporting)

README.md
=> added centos dependencies

lib/api.js, package.json
* Closes https://github.com/Storj/storjshare-gui/issues/578
=> fix share restart after max shares running

dockerfiles/storjshare-daemon-alpine.dockerfile
Alpine Linux Dockerfile for much slimmer docker images
=> Alpine Dockerfile

.jshintrc, README.md, bin/storjshare-create.js, bin/storjshare-daemon.js, bin/storjshare-logs.js, example/farmer.config.json, lib/api.js, lib/config/farmer.js, package.json, test/api.unit.js
=> Rotating log files

dockerfiles/get_dep_ver.ps1
-Allows automated pulling the latest dependencies for the windows docker image
-More efficient and smaller windows image
=> updated Windows dockerfile for storjshare-daemon

bin/storjshare-create.js
=> Add logger verbosity to storjshare create options

bin/storjshare-create.js, bin/storjshare-status.js, example/farmer.config.json, lib/api.js, lib/config/farmer.js, lib/utils.js, script/farmer.js, test/api.unit.js
* Closes #172 
* Closes #101 
* Closes #164 
* Closes #32 
* Closes #193
=> Closing issues

lib/utils.js, test/utils.unit.js
=> Invalid storage size print out missing bytes

snap/snapcraft.yaml
=> bugfix snapcraft

package.json
=> bugfix free space query df -kP

bin/storjshare-status.js
=> print out dataReceived counter instead of percentage

package.json, script/farmer.js
We can check free space to prevent "no space on device errors" with https://github.com/Storj/core/pull/730
=> Disable runSpaceCheck for now

example/farmer.config.json, lib/config/farmer.js
depends on https://github.com/Storj/core/pull/733
=> remove maxOfferConcurrency

README.md
=> LTS version of the Node.js

bin/storjshare-status.js
Depends on https://github.com/Storj/core/pull/739
=> switch from offer to alloc counter

package.json
=> Use bugfix version of 'daemon'

bin/storjshare-status.js
=> Rename 'Share' to 'Node' in storjshare status command

CONTRIBUTING.md, README.md
URLs updated to use HTTPS protocol where appropriate to improve security and privacy.
=> Update: HTTP -> HTTPS

lib/utils.js
@aleitner 
Adds a better error message for this issue:
* Closes https://github.com/Storj/storjshare-daemon/issues/301
=> specifies missing directory for invalid directory error
