dockerfiles/storjshare-daemon-ubuntu.dockerfile, dockerfiles/storjshare-daemon-win.dockerfile
Initial Release of the Windows storjshare-daemon-win docker file
Should be able to be run on Windows Server 2016 with Containers enabled and Windows 10 with containers enabled
https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install
=> storjshare-daemon-win.dockerfile Initial Release

script/farmer.js
Make the raw bytes of used space available via rpc in addition to a formatted string.
=> Add used space in raw bytes as well

bin/storjshare.js
Hello colleagues
Maybe I made errors with work in github, but please write comments about my pull request.
Part bash script for check status storj nodes
```bash
x=`storjshare -V`
echo $x
```
When I started bash script, I saw echo output
```bash
storjshare-create.js storjshare-daemon.js storjshare-destroy.js storjshare.js storjshare-killall.js storjshare-load.js storjshare-logs.js storjshare-restart.js storjshare-save.js storjshare-start.js storjshare-status.js storjshare-stop.js daemon: 2.5.4, core: 6.4.2, protocol: 1.1.0
```bash
All files in current folder!
But I need only version daemon & core version & protocol version
Because javascript include '*', I saw all files in current folder and required data (daemon/core/protocol version)
```bash
.version(`\n  * daemon: ${version}, core: …
```
=> Remove symbols

package.json
* Closes https://github.com/Storj/storjshare-daemon/issues/144
=> bugfix fd-diskspace allow dot on osx and linux

snap/snapcraft.yaml
New configuration will be created under /home/$user/snap/storjshare/...
The plug interface will make sure the app are able to access the config file in user directory else user have to use --devmode when install the snap.
=> Allow snap app to access $HOME directory.

script/farmer.js
This PR will add the conversion of an optional config field `maxShardSize` from human readable values like 100MB to bytes.
This allows each node to not respond with storage offers to contracts with a higher shard size than the configured one in the config.
Requires https://github.com/Storj/core/pull/702 to be merged to work, but can be merged before, it wont do harm ;)
=> Add maxShardSize option

README.md, bin/storjshare-create.js, example/farmer.config.json
The sample config and daemon options were updated to specifiy STORJ instead of SJCX but the "BTC" in the sample config file was not updated to reflect that STORJ is an ERC20 token.
=> Fix BTC to ERC20 in sample config

lib/utils.js, test/utils.unit.js
Since users can sometimes copy the wrong address, especially if they are new to the technology, we want to stop them in case they accidentally copy the contract or contract owner addresses. They should not be allowed to farm on these because they won't receive the proceeds from their farming, and there has been a problem in the past with people farming to the SJCX owner address.
=> Disallow contract and owner addresses

lib/utils.js, test/utils.unit.js
This method will allow completion of [issue #577 in storjshare-gui](https://github.com/Storj/storjshare-gui/issues/577) by providing the gui with a method to check whether or not a port is open. This method is to be used sparingly as it could take a second or two for node to spin up a server, and should only be used as a final check before the user leaves that page of the wizard. I will add features to the gui necessary to convey that the program is validating a port.
=> Add util method portIsAvailable

bin/storjshare-status.js, script/farmer.js
This is to implement https://github.com/Storj/storjshare-gui/issues/513
Use the values provided by farmer to determine port and connection type and display when user runs storjshare status
Requires https://github.com/Storj/core/pull/701 be merged.
=> Ease-of-Use improvements in daemon

bin/storjshare-daemon.js, bin/storjshare-destroy.js, bin/storjshare-killall.js, bin/storjshare-load.js, bin/storjshare-logs.js, bin/storjshare-restart.js, bin/storjshare-save.js, bin/storjshare-start.js, bin/storjshare-status.js, bin/storjshare-stop.js, lib/utils.js
This PR will add the optional cli option `-r, --remote <hostname:port>  hostname and optional port of the daemon`. This allows the storjshare-daemon commands to be executed on a remote storjshare-daemon whos rpcPort is reachable. The util method `connectToDaemon` and `checkDaemonRpcStatus` have been modified to support a third optional argument, the hostname. If nothing has been entered, hostname will default to `127.0.0.1` as it did implicitly before and port will default to `config.daemonRpcPort` as before.
The main reason for this is to manage docker instances more easily, but it can be used for non-local machines as well.
=> Add hostname:port option

snap/snapcraft.yaml
A recent snapcraft update lets you use the git revision as the version. If the snap is built from an annotated tag, that tag will be the version.
=> use the git tag as the version for the snap

script/farmer.js
Workaround for https://github.com/Storj/core/issues/703
When NAT reflection is disabled we can't tell if a port is truly closed or if we simply are not able to loopback. If this is the case, don't show the port as red & closed, simply do not color green.
=> Fix port status to not show red if unable to determine if port is open

bin/storjshare-status.js
Seems like an easy but effective fix (Although another option is to look at truncating the decimal places before the unit type - this is only 2 characters more)
This is enough for 4 characters (e.g 1023), the dot and 2 decimal places before the unit type (MB, GB etc).
Resolves https://github.com/Storj/storjshare-daemon/issues/124
=> Resolve storjshare status share truncated.

bin/storjshare-status.js
Now valid json. Fix as per :https://github.com/Storj/storjshare-daemon/issues/213
Tested locally and output validated with https://jsonlint.com.
Fix suggestion originanlly by @buckley310
=> Fix storjshare status --json response to be valid

lib/api.js, lib/utils.js, test/utils.unit.js
- Fix the `_isValidSize()` function to be more correct
- If the `storageAllocation` doesn't have a size specifier, default to bytes and add `B` to the end of the value. This could be left over from older configs.
=> [WIP] Repair config on read

package.json
@braydonf please test this on OSX. The reason my first bugfix was not working is a different -P output on OSX. Should now be fixed.
=> bugfix free space query df -kP

README.md, example/farmer.config.json, lib/config/farmer.js, lib/utils.js, package.json, script/farmer.js
Implements https://github.com/Storj/sips/blob/master/sip-0006.md
Part of: Storj/integration#5
* closes #242
=> Remove bridgeUri from config

lib/utils.js, test/utils.unit.js
This can also be solved by using `info.free` instead of `info.available`, though this check isn't necessary as there is a free space check before accepting new shards to prevent disk "no space left on device" errors and crashing.
There is a case where `available` will be missing 5% as it is reservered for root user that can lead to an issue where on startup the amount allocated would give an error. This is technically not incorrect.
Thanks @tempestb for helping to debug.
Closes: https://github.com/Storj/storjshare-gui/issues/670
=> Remove free + used space check

lib/utils.js
"bytes" Node.js module parses "8TB" in the config as 8\*2^40B but the daemon was limited to 8\*10^12B.
=> Allow nodes with an allocated space size of up to 8TiB.

lib/utils.js, package.json, test/utils.unit.js
If a payout address uses mixed case, it must be according to [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md).
Only lower- or only uppercase addresses are still valid as well.
=> Verify checksum of Ethereum payout addresses

lib/api.js, script/farmer.js, test/api.unit.js
close #281
I reset the share values when the share is stopped to the following:
1. Bridges set to  "disconnected".
2. The delta set to 0.
3. Peers set to 0.
4. Uptime set to 0ms.
5. Restarts count set to 0.
This should also fix similar problems in the GUI.
Here is a screen shot of the fix:
=> Fix share status when stopped.

bin/storjshare-status.js
Give Farmer a better advice that Tunnel Connections arent good for neither performance nor stability.
=> Mark Tunnel Connections as bad

example/farmer.config.json
Tunnel Connections are not stable enough with regards to SIP09 and are also bad for performance.
Further it increases the chances to mark a legit farmer as a cheater when creating the payout sheet, when multiple Payment Addresses are running over a single IP.
=> Set default Tunnel Configuration to "not allowed"

README.md
There are headers for all sections of the readme file, except for the install package section.
For coherence but also for accessibility reasons it might be reasonable to also have a title here.
=> Add a title for Install section in the readme file
